"""add match breakdown

Revision ID: d711a46f8947
Revises: 0566a8bba08d
Create Date: 2026-08-08 23:24:04.880721
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd711a46f8947'
down_revision: Union[str, None] = '0566a8bba08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breakdown', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('breakdown')

    # ### end Alembic commands ###
